"""Generate Markdown documentation for ComfyUI-ProperPixelArt nodes from schemas."""

from __future__ import annotations

import asyncio
import importlib.util
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import comfy_api.latest as comfy_api


def format_value(value: Any, io_type: str | None = None) -> str:
    """Format a value for Markdown table cells."""
    if value is None:
        return "-"
    if isinstance(value, bool):
        return "True" if value else "False"
    if io_type == "FLOAT" and isinstance(value, (int, float)):
        return str(float(value))
    if isinstance(value, float):
        return str(value)
    if isinstance(value, str):
        return f"`{value}`" if value != "" else '`""`'
    return str(value)


def format_range(min_val: Any, max_val: Any, io_type: str | None = None) -> str:
    """Format min/max range for Markdown table cells."""
    if min_val is None and max_val is None:
        return "-"
    if min_val is not None and max_val is None:
        return f">= {format_value(min_val, io_type)}"
    if min_val is None and max_val is not None:
        return f"<= {format_value(max_val, io_type)}"
    min_str = format_value(min_val, io_type)
    max_str = format_value(max_val, io_type)
    return f"{min_str} .. {max_str}"


def format_options(options: list[Any] | None) -> str:
    """Format Combo options for Markdown table cells."""
    if not options:
        return "-"
    return ", ".join(f"`{opt}`" for opt in options)


def load_extension_nodes() -> list[type[comfy_api.io.ComfyNode]]:
    """Load the extension nodes dynamically in the same way as tests."""
    root = Path(__file__).resolve().parents[1]
    module_name = "properpixelart_docs_pack"
    spec = importlib.util.spec_from_file_location(
        module_name,
        root / "__init__.py",
        submodule_search_locations=[str(root)],
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load extension spec from {root / '__init__.py'}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)

    async def _get_nodes() -> list[type[comfy_api.io.ComfyNode]]:
        extension = await module.comfy_entrypoint()
        await extension.on_load()
        return await extension.get_node_list()

    return asyncio.run(_get_nodes())


def generate_nodes_markdown(
    nodes: list[type[comfy_api.io.ComfyNode]] | None = None,
) -> str:
    """Generate Markdown text representing the node schemas."""
    if nodes is None:
        nodes = load_extension_nodes()

    lines: list[str] = [
        "# Nodes",
        "",
        "This file is automatically generated from node schemas by `just docs`.",
        "",
    ]

    for node_cls in nodes:
        schema = node_cls.GET_SCHEMA()

        display_name = schema.display_name or schema.node_id
        lines.append(f"## {display_name}")
        lines.append("")
        lines.append(f"- **Node ID**: `{schema.node_id}`")
        lines.append(f"- **Category**: `{schema.category}`")
        if schema.description:
            lines.append(f"- **Description**: {schema.description}")
        lines.append("")

        lines.append("### Inputs")
        lines.append("")
        lines.append("| Name | Type | Default | Range | Options | Optional | Tooltip |")
        lines.append("| --- | --- | --- | --- | --- | --- | --- |")

        for inp in schema.inputs:
            name = inp.id
            io_type = inp.get_io_type()
            default_val = getattr(inp, "default", None)
            min_val = getattr(inp, "min", None)
            max_val = getattr(inp, "max", None)
            options = getattr(inp, "options", None)
            if getattr(inp, "upload", None) is not None:
                options = None
            optional = "Yes" if inp.optional else "No"
            tooltip = inp.tooltip or "-"

            default_str = format_value(default_val, io_type)
            range_str = format_range(min_val, max_val, io_type)
            options_str = format_options(options)

            lines.append(
                f"| `{name}` | `{io_type}` | {default_str} | {range_str} | {options_str} | {optional} | {tooltip} |"
            )

        lines.append("")
        lines.append("### Outputs")
        lines.append("")
        lines.append("| Name | Type | Tooltip |")
        lines.append("| --- | --- | --- |")

        for out in schema.outputs:
            name = (
                out.display_name
                if out.display_name
                else (out.id if out.id and not out.id.startswith("_") else out.io_type)
            )
            io_type = out.get_io_type()
            tooltip = out.tooltip or "-"
            lines.append(f"| `{name}` | `{io_type}` | {tooltip} |")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_nodes_markdown(output_path: Path | str | None = None) -> Path:
    """Generate and write the nodes documentation to file with LF line endings."""
    if output_path is None:
        root = Path(__file__).resolve().parents[1]
        path = root / "docs" / "nodes.md"
    else:
        path = Path(output_path)
    content = generate_nodes_markdown()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content.encode("utf-8"))
    return path


def main() -> None:
    write_nodes_markdown()


if __name__ == "__main__":
    main()
