name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true

      - name: Install dev dependencies
        run: uv sync --dev

      - name: Lint / Format
        run: |
          uv run ruff check
          uv run ruff format --check

      - name: Run tests
        run: uv run pytest
