name: ComfyUI master compatibility

on:
  schedule:
    - cron: "23 4 * * 1"

permissions:
  contents: read

jobs:
  compatibility:
    uses: ./.github/workflows/comfyui.yml
    with:
      os: '["ubuntu-latest"]'
      comfyui_ref: master
